markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_name: Digital Hub

extra:
  site: https://alb-car.github.io/docs
  sdk_site: https://scc-digitalhub.github.io/sdk-docs
  docs_version: !ENV [DOCS_VERSION, 'current']
  versions: !ENV [VERSIONS]
  portals:
    - name: User
      path: ""
    - name: Dev
      path: "/dev"
    - name: Admin
      path: "/admin"

theme:
  name: material
  custom_dir: ../custom/
  features:
    - navigation.expand
    - navigation.path
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
