name: deploy-docs
run-name: Build and deploy docs
on: [push]
permissions:
  contents: write
jobs:
  deploy-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install mkdocs-material
      - run: |
          git fetch --prune --unshallow --tags
          echo ${{ github.event }}
          echo ${{ github.event.action }}
          echo ${{ github.action }}
          git checkout main
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|python versions_string.py)
          cd user && mkdocs build && cd ..
          cd dev && mkdocs build && cd ..
          cd admin && mkdocs build && cd ..
          mv user/site ./site
          mv dev/site site/dev
          mv admin/site site/admin
      - run: |
          git checkout gh-pages
          cp -r site/* .
          rm -r site
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Workflow docs - Current" --allow-empty
          git push
  deploy-versioned:
    needs: deploy-current
    if: github.ref_name != 'main' && github.ref_name != 'gh-pages'
    runs-on: ubuntu-latest
    env:
      DOCS_VERSION: v:${{ github.ref_name }}
      USER_STYLESHEETS_PORTAL_SELECTION: ../stylesheets/portal_selection.css
      USER_STYLESHEETS_COLORS: ../stylesheets/colors.css
      OTHERS_STYLESHEETS_PORTAL_SELECTION: ../../stylesheets/portal_selection.css
      OTHERS_STYLESHEETS_COLORS: ../../stylesheets/colors.css
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install mkdocs-material
      - run: |
          git fetch --prune --unshallow --tags
          echo ${{ github.event }}
          echo ${{ github.event.action }}
          echo ${{ github.action }}
          git checkout ${{ github.ref_name }}
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|python versions_string.py)
          cd user && mkdocs build && cd ..
          cd dev && mkdocs build && cd ..
          cd admin && mkdocs build && cd ..
          mkdir ./site
          mv user/site site/${{ github.ref_name }}
          mv dev/site site/${{ github.ref_name }}/dev
          mv admin/site site/${{ github.ref_name }}/admin
      - run: |
          git checkout gh-pages
          cp -r site/* .
          rm -r site
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git add --all
          git commit -m "Workflow docs - Versioned" --allow-empty
          git push
