name: update-docs
run-name: Generate and deploy docs
on:
  create:
    branches:
      - '**'
  push:
    branches-ignore:
      - gh-pages
permissions:
  contents: write
jobs:
  redeploy-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install mkdocs-material
      - run: |
          git fetch --prune --unshallow --tags
          this_branch=${{ github.ref_name }}
          if [ "$this_branch" == "main" ]; then
            this_branch=current
          fi
          echo "Triggered on branch '${this_branch}' by event '${{ github.event_name }}'"
          export VERSIONS=$(echo `git branch -r --format='%(refname:short)'`|python versions_string.py)
          echo "Versions are: ${VERSIONS}"
          for v in ${VERSIONS//,/ }
          do
            if [ "${{ github.event_name }}" == "create" ] || [ "$v" == "$this_branch" ]; then
              echo "Deploying docs for: $v"
              if [ "$v" != "current" ]; then
                echo "Behaviour for any non-main branch"
              else
                echo "Special behaviour for main"
              fi
            fi
          done